# Site settings
title: EleanorFrajka LabLog # type your own lablog title here

description: > # this means to ignore newlines until "baseurl:"
  This is an experiment in an open science-type notebook.  
  Find my static website at http://eleanorfrajka.com.
baseurl: "/lablog" # the subpath of your site, e.g. /blog/
url: "http://eleanorfrajka.github.io" # the base hostname & protocol for your site
include: [ _assets , _projects ]
destination: "/Users/eddifying/GitProjects/eleanorfrajka.github.io/lablog/"

name : Eleanor Frajka-Williams
email : e.frajkawilliams@gmail.com
github_username: eleanorfrajka
twitter_username: eleanorfrajka
website : http://eleanorfrajka.com

# Build settings
markdown: kramdown
kramdown:
  input: GFM

noindex: true # if true, google will ignore your pages!

defaults:   # overwrite with in YAML frontmatter, e.g. 'place: New York'
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      place:  # default Geolocation of posts.
      author: # default author for posts (for multi-authoring)
