exclude: [ _posts/source ]
highlighter: pygments
safe: false
paginate: 6

scholar:
  style: apa
  sort_by: year
  order: descending
  source: ./biblio
  bibliography: totall.bib
  
tag_page_layout: tag_page
tag_page_dir: tag

markdown: Pandoc
pandoc:
  extensions: 
    - smart
    - mathjax
    - bibliography: /Users/eddifying/Dropbox/library-bibtex/totall.bib
    

author:
  name: Eleanor Frajka-Williams
  givenName: Eleanor
  familyName: Frajka-Williams
  github: eleanorfrajka
url: http://eleanorfrajka.com
title: Lab Notebook for Eleanor Frajka-Williams
name: Lab Notebook for Eleanor Frajka-Williams
