exclude: [ _posts/source ]
highlighter: pygments
safe: false
paginate: 6

scholar:
  style: apa
  sort_by: year
  order: descending
  source: ./biblio
  bibliography: labnotebook.bib
  
tag_page_layout: tag_page
tag_page_dir: tag

markdown: Pandoc
pandoc:
  extensions: 
    - smart
    - mathjax
    - bibliography: /Users/eddifying/Dropbox/library-bibtex/totall.bib
    

author:
  name: Mark E. Madsen
  givenName: Mark
  familyName: Madsen
  github: mmadsen
url: http://notebook.madsenlab.org
title: Lab Notebook for Mark E. Madsen
name: Lab Notebook for Mark E. Madsen
